BUG/MAINT:  TIMED SABER version and github actions
pysat/pysatNASA pull request #128
Opened 2022-10-19 20:21 UTC by jklenzing

# Description

TIMED SABER released a new version of data, and the filenames and directories have changed.  Updates to use the latest.

Also updates github actions python version to 3.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Standard tests.  Since remote location and filename have changed, files will not download with old code.

## Test Configuration
* Operating system: Mac OS X Monterrey
* Version number: Python 3.8.11

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes
- [x] Update zenodo.json file for new code contributors

2022-10-21 18:13 UTC, jklenzing commented
last pull before I can create the RC

2022-10-21 18:32 UTC, aburrell requested changes

2022-10-21 18:32 UTC, aburrell commented on .github/workflows/main.yml
> +      uses: actions/setup-python@v3
```suggestion
      uses: actions/setup-python@v4
```

Found out there's a newer version.

2022-10-21 18:32 UTC, aburrell commented on CHANGELOG.md
> +  * Update github actions to v3
```suggestion
  * Update GitHub actions to the latest versions
```

2022-10-21 18:32 UTC, aburrell commented on CHANGELOG.md
> +  * Updated filenames for timed saber
```suggestion
  * Updated filenames for TIMED SABER
```

2022-10-21 20:04 UTC, jklenzing commented
Code is updated and running successfully, but coveralls is broken (failing here and other pulls)

2022-10-26 13:25 UTC, jklenzing commented
Coveralls working again.  Ready for review

2022-10-26 14:31 UTC, aburrell approved these changes

2022-10-26 14:32 UTC, merged

2022-10-27 19:20 UTC, rstoneback commented
Thanks @jklenzing and @aburrell