ENH: REACH data
pysat/pysatNASA pull request #206
Opened 2023-09-18 18:05 UTC by jklenzing

# Description

- Adds reach dosimeter data
- Fixes docstring copy paste issues

# Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

```
import datetime as dt
import pysat
import pysatNASA

reach = pysat.Instrument(inst_module=pysatNASA.instruments.reach_dosimeter, inst_id='101')
reach.remote_file_list()

reach.download(dt.datetime(2017, 4, 10))
reach.load(date=dt.datetime(2017, 4, 10))
reach.data

```

**Test Configuration**:
* Operating system: Ventura
* Version number: Python 3.9.12

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes
- [x] Update zenodo.json file for new code contributors

If this is a release PR, replace the first item of the above checklist with the release
checklist on the wiki: https://github.com/pysat/pysat/wiki/Checklist-for-Release

2023-09-18 18:07 UTC, jklenzing commented
Still needs:
- [ ] acknowledgement string (can I import this from cdasws?)
- [ ] reference string
- [ ] double-check meta translation

2023-09-20 14:13 UTC, jklenzing commented
The acknowledgement string is more complicated than expected. Using standard copy paste for now, documented potential paths forward in #207.

2023-10-02 18:28 UTC, jklenzing commented
Note for testing:
```
import pysat
import pysatNASA
reach = pysat.Instrument(inst_module=pysatNASA.instruments.reach_dosimeter, inst_id='101')
reach.acknowledgements
```
yields
```
'Please load a file for full acknowledgments.'
```
Assuming you have downloaded files, running
```
reach.load(date=reach.files.files.index[0])
reach.acknowledgements
```
will then yield the full acknowledgement string.

2023-10-02 18:41 UTC, aburrell commented on pysatNASA/instruments/methods/reach.py
> +                   ))}
```suggestion
                             "AEROSPACE REPORT NO. TOR-2021-01076"))))}
```

2023-10-02 18:41 UTC, aburrell commented on pysatNASA/instruments/reach_dosimeter.py
> +        inst = pysat.Instrument('icon', 'ivm', inst_id='a', tag='')
Fix example

2023-10-02 18:41 UTC, aburrell commented on pysatNASA/instruments/reach_dosimeter.py
> +    inst_id : string
```suggestion
    tag : str
        tag name used to identify particular data set to be loaded.
        This input is nominally provided by pysat itself.
    inst_id : str
```

2023-10-02 19:01 UTC, jklenzing commented on pysatNASA/instruments/reach_dosimeter.py
> +        inst = pysat.Instrument('icon', 'ivm', inst_id='a', tag='')
```suggestion
        inst = pysat.Instrument('reach', 'dosimeter', inst_id='101', tag='')
```

2023-10-03 12:52 UTC, aburrell commented
Ok, the data loads well, but the global file attributes in MetaHeader have problems.  A benign example that I would let pass is  `reach.meta.header.Notes` is `nan`.  A malignant example is `Temperature_Sensitivity_43-65_deg`, whose string format is not appropriate for an attribute name and so is not accessible.  I think this can be fixed by replacing the `-` with a `_` in the load function.

2023-10-03 12:55 UTC, aburrell requested changes
Fix load routine so that all meta header attributes are accessible using standard attribute access method.

2023-10-04 19:55 UTC, jklenzing commented on pysatNASA/instruments/reach_dosimeter.py
> +import functools
```suggestion
import functools
import numpy as np
```

2023-10-05 14:54 UTC, aburrell approved these changes

2023-10-05 15:04 UTC, merged