LGL: Update controlled information review statement for clarity
pysat/pysatNASA pull request #251
Opened 2024-12-18 22:52 UTC by rstoneback

# Description

Addresses #(issue)

Update controlled information statement for clarity and to ensure pysat's legal rights are maintained.

# Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Updated comments. No need for additional testing.

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes
- [x] Update zenodo.json file for new code contributors

If this is a release PR, replace the first item of the above checklist with the release
checklist on the wiki: https://github.com/pysat/pysat/wiki/Checklist-for-Release

2024-12-20 01:26 UTC, rstoneback commented
So the doc error about the admonition wasn't causing the documentation tests to fail but it was incorrect as written. That is fixed. Still trying to sort out what the inline_table_error thing is all about. This error is coming up in documentation I didn't modify.

2024-12-20 15:37 UTC, rstoneback commented
extras_require issue now tracked in report #252

2024-12-20 15:39 UTC, rstoneback commented
Friendly heads up to @jklenzing given historical ownership but recognizing NASA has stopped support, plus government may be shutting down.

2024-12-20 16:53 UTC, rstoneback commented
NASA websites are down causing the current documentation check errors. The previous errors are indeed fixed by my changes.

2025-01-02 16:00 UTC, rstoneback commented
Oh, given https://github.com/pysat/pysatMissions/pull/124 it looks like some folks are still active

2025-01-08 20:46 UTC, jklenzing requested changes

2025-01-08 20:46 UTC, jklenzing commented on CHANGELOG.md
> +* Bug Fixes
```suggestion
* Documentation
```

2025-01-14 21:15 UTC, jklenzing approved these changes

2025-01-15 13:55 UTC, merged