STY: setup.cfg
pysat/pysatNASA pull request #67
Opened 2021-05-20 18:40 UTC by jklenzing

Avoids duplication in requirements.

Should be the last pull opened before the release candidate.

2021-05-26 18:25 UTC, JonathonMSmith requested changes

2021-05-26 18:25 UTC, JonathonMSmith commented on setup.cfg
> +  install_requires =file: requirements.txt
Maybe this should be 'install_requires = file: requirements.txt'

2021-05-26 18:25 UTC, jklenzing commented on setup.cfg
> +  install_requires =file: requirements.txt
```suggestion
  install_requires = file: requirements.txt
```

2021-05-27 01:04 UTC, jklenzing commented on setup.cfg
> +  install_requires =file: requirements.txt
I'm fine with keeping separate lists

2021-05-27 01:04 UTC, jklenzing commented
Closing since we should not import directly from requirements.txt

2021-05-27 01:04 UTC, closed without merging